/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hangman;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void createGameReturnsValidUUID() {
        // arrange

        // act
        var result = App.createGame();

        // assert
        assertNotNull("create game should return an id", result);
    }
}
